## Site Meta ##
# The title of the website.
title: "Cloud Skills: Sketchnotes Edition"
# The description of the website
description: "A collection of sketchnotes from talks, docs and trainings, that provide more insight into Cloud Computing (general) and Microsoft Azure (specific)."
# Keywords/tags for you site.
keywords: "azure, cloud, sketchnotes, visual, skilling, technology, storytelling"
# Your copyright message.
copyright: "Copyright &copy; 2021 - Nitya Narasimhan (@nitya)."

## Site Configurations ##
# 1st heading of the site.
header: "Sketchnotes"
# 2nd heading/sub heading of the website.
subheader: "Cloud Skills Visualized"
# A description/bio of the website.
bio: "A sketchnotes repository for all things Cloud Computing and Azure."
social:
  # Your Twitter username.
  twitter_username: "SketchTheDocs"
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: "SketchTheDocs"
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
